## 1. What does Pandas stand for?
### Pandas is a portmanteau of PANel DAta.

## 2. What are the 2 collections used in Pandas?
### Series and DataFrames
## 3. Name 4 things Pandas can do for us.
### Data cleaning, normalization, visualization, and inspection.
## 4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
### You would use df.sort_values( by, inplace=True)
## 5. What is a CSV?
### A Comma Separated Values file, effectively a file where the data is formatted in tables with a comma separating the values,  hence the name
## 6. When cleaning data what values do we not like in our data?
### Null or missing values

In [21]:
#Question 7

import pandas as pd
import numpy as np
import copy

array7 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], ])
array7 = np.reshape(array7, (2, 3, 2))

#Question 8

array8 = np.linspace(0, 20, 6)

#Question 9
array8Copy = copy.deepcopy(array8)




In [16]:
array7

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [3]:
#Question 10

catArray0 = np.array([[25, 16]])
catArray1 = np.array([[11, 2], [13, 4]])
catArray2 = np.array([[7, 81], [5, 6], [11, 12]])
newArray = np.concatenate ((catArray0, catArray1, catArray2))
newArray

array([[25, 16],
       [11,  2],
       [13,  4],
       [ 7, 81],
       [ 5,  6],
       [11, 12]])

In [4]:
#Question 11
sortedArray = np.sort(newArray, axis = 0)
sortedArray

array([[ 5,  2],
       [ 7,  4],
       [11,  6],
       [11, 12],
       [13, 16],
       [25, 81]])

In [ ]:
#Question 12
# Did not understand the question, awaiting clarification

In [37]:
#Question 13
arrayOne = np.array([10, 11, 12, 13, 14, 15, 16, 17])
arrayTwo = np.array([20, 21, 22, 23, 24, 25, 26, 27])
arrayThree = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

array13 = np.concatenate((arrayOne, arrayTwo, arrayThree), axis=0)
comboArray = np.sort(array13)
comboArray

array([ 0,  1,  2,  3,  4,  5,  6,  7, 10, 11, 12, 13, 14, 15, 16, 17, 20,
       21, 22, 23, 24, 25, 26, 27])

In [53]:
print(comboArray[1])
print(comboArray[2:])
print(comboArray[3:13])
print(comboArray[-6:])
print(comboArray[-11::-1])
print(comboArray[16::2])
print(comboArray[-1::5]) #    - print sec7 - from the last element moving forward, every 5th element. This is a nonsense statement. There is no 5th element from the last element, nor is there any way to move forward through the array from the last element.


1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14]
[22 23 24 25 26 27]
[15 14 13 12 11 10  7  6  5  4  3  2  1  0]
[20 22 24 26]
[27]


In [62]:
#Question 15
stuffIngredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name= "Ingredient")
stuffQuantity = pd.Series([4, 1, 2, 1], name= "Quantity")
stuffUnit = pd.Series(["Cups", "cup", "Large", "Can"], name = "Unit")

df = pd.DataFrame(stuffIngredients).join(stuffQuantity).join(stuffUnit)
df

Ingredient  Quantity   Unit
0      Flour         4   Cups
1       Milk         1    cup
2       Eggs         2  Large
3       Spam         1    Can

In [67]:
studentDatadict ={
         'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
         'Height': [5.1, 6.2, 5.1, 5.2],
         'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
         'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
         'Age': [21, 23, 24, 21],
         'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
         'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
studentData = pd.DataFrame(studentDatadict)
dessert = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData["Favorite Dessert"] = dessert
studentData.sort_values(by = ["Name", "address"], inplace = True)

Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

  Favorite Dessert  
3     Carrot Halwa  
2          waffels  
0        ice cream  
1     Cashew Fudge

In [68]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv("cows_and_goats.csv")

In [74]:
vegetables = pd.DataFrame({
   "Vegetable" :["Carrot", "Beet"],
   "Color" :["NULL", "Red"]
   })
   
vegetables.to_csv("vegetables.csv")

In [79]:
placeHolder = pd.read_csv("vegetables.csv")
placeHolder.fillna("Orange", inplace=True)
placeHolder.to_csv("vegetablesUpdated.csv")
